name: auctioneer
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  firebase_auth: ^1.2.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  font_awesome_flutter: ^9.0.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.4
  lottie: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.8+4
  very_good_analysis: ^2.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
